### ISSUE TITLE
login does nothing

### ISSUE THREAD

**Issue by neosin** [Paratron/mesa#1]
hi 
1. I tried opera, firefox and IE 10 and cannot login after installing (using default adminMail/adminPassword)
2. visiting the root site without login results in error

```
require(lib/config/routes.php): failed to open stream: No such file or directory in \cms\php\frontend.php on line 21
```

I can confirm that there is no folder called config and no file called routes.php in lib folder

**Comment by Paratron** [comment]
Whoa, I have no idea how you found out about this project, but I sadly have to disappoint you right now: The project status is veeeery far from being usable by anyone but me right now.

I'll put more time into it, soon - I promise, but right now, it won't do anything more but letting people login and click a bit around.
Looks like your bug is related to older code - I'll go and push the latest sources, but this still won't help much since the frontend routers for actual page rendering aren't even in place, yet :)
